version: '2'
services:
  web:
    image: treeptik/devoxx2018
    restart: unless-stopped
    labels:
      - "traefik.frontend.rule=Host:#APP#.167.99.84.161.xip.io"
      - "traefik.backend=#APP#"
      - "traefik.port=8080"
      - "traefik.frontend.entryPoints=http"

  database:
    image: postgres:10
    volumes:
      - "/mnt/btrfs/pg-#APP#:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    restart: unless-stopped
    labels:
      - "traefik.enable=false"
      
networks:
  default:
    external:
      name: skynet
